name: Daily Pipeline + Update HF API DB

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  run-pipeline:
    runs-on: ubuntu-latest

    env:
      NEWSAPI_API_KEY: ${{ secrets.NEWSAPI_API_KEY }}
      GROQ_API_KEY: ${{ secrets.GROQ_API_KEY }}

    steps:
      - name: Check out GitHub repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: pip install -r backend/requirements.txt

      - name: Run pipeline
        run: python backend/main.py

      - name: Run monitoring
        run: python backend/monitor.py

      - name: Commit updated SQLite DB back to GitHub
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          git add data/news.db

          if git diff --cached --quiet; then
            echo "No GitHub DB changes to commit."
          else
            git commit -m "Update news.db"
            git push
          fi

      - name: Clone Hugging Face Space repo
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          git clone https://Signe22:$HF_TOKEN@huggingface.co/spaces/Signe22/Article_Data_API hf-space

      - name: Copy only the DB into Hugging Face Space repo
        run: |
          mkdir -p hf-space/data
          cp data/news.db hf-space/data/news.db

      - name: Commit and push DB update to Hugging Face Space
        working-directory: hf-space
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          git add data/news.db

          if git diff --cached --quiet; then
            echo "No HF DB changes to commit."
          else
            git commit -m "Update data/news.db"
            git push
          fi
